### ISSUE TITLE
Fun Fact inconsistencies

### ISSUE THREAD

**Issue by katevda** [oSoc20/urban-brussels-api#34]
~~Wist je dat het gebouw Manufacture Royale de pianos François Berden et Cie - Confiserie Chocolaterie Antoine de volgende typologieën heeft: burgerwoning, werkplaats (ambachtelijk), tentoonstellingszaal, fabriek en herenhuis.
& Wist je dat het gebouw Scholencentrum Sacré-Coeur de Lindthout de volgende typologieën heeft: orgel, school, conservatorium/kunstacademie, kasteel en kerk/kathedraal/basiliek.
& Wist je dat het gebouw Maria Assumptalyceum en Basisschool, Ecole Primaire en Lycée Maria Assumpta en Institut Christ-Roi de volgende typologieën heeft: kinderbewaarplaats, school, pastorie, parochiezaal en kerk/kathedraal/basiliek.
& Wist je dat het gebouw Josaphatpark de volgende typologieën heeft: kiosk, sportcomplex, fontein, Zitbank, brug en beeldhouwwerk en herdenkingsmonument.
& Wist je dat het gebouw Voormalige hoofdzetel van S.A. Les Tramways bruxellois de volgende typologieën heeft: burgerwoning, kantoorgebouw, bijgebouwen, gelijkvloers met handelszaak en herenhuis.
& Wist je dat het gebouw Brusilia de volgende typologieën heeft: pompstation, sportcomplex, appartementsgebouw, winkel en warenhuis/supermarkt.
=> the typologies in these fun facts are grey boxes that lead to the building list but don't actually add to the search
-- @jbelien : Moved (back) to Front-End : https://github.com/oSoc20/urban-brussels/issues/65~~

---

~~Wist u dat er een gebouw is met 46 verschillende bijdragers ? Dit gebouw is Gemeentehuis van Sint-Gillis. 
=> The building name here links to the iris monument page instead of our own detail page for it. (This is also the only building name that links to anything, so either link every building name or none?)~~

---

~~undefined
=> Even when I wait this still stays, but might have something to do with clicking on a fun fact tag, going to the building list and then just going back in my browser instead of clicking home (because the home button is not published yet)
-- @jbelien : Moved (back) to Front-End : https://github.com/oSoc20/urban-brussels/issues/62~~

---

~~Less of an issue:
Wist u dat het gebouw Abdij van Dieleghem - voormalige prelaatwoning dateert van 1775, waardoor het één van de oudste gebouwen in Brussel is.
=> building name can link to detail page (has no links now) + maybe also create a tag for years? Or is search on year not enabled right now?~~
-----> Building name can't link to detail page since there is no specific page for each building
-----> Search by year put on TODO list

~~Inconsistencies between 'Wist u' and 'Wist je' for the Dutch fun facts (can be 'wist je dat' overall imo)~~

**Comment by jbelien** [comment]
> Saviez-vous qu'il y existe 143 typologies différentes ?

There is a "y" too much.
"Saviez-vous qu'il existe 143 typologies différentes ?"

**Comment by Speedbuilder** [comment]
> 
> 
> > Saviez-vous qu'il y existe 143 typologies différentes ?
> 
> There is a "y" too much.
> "Saviez-vous qu'il existe 143 typologies différentes ?"

RESOLVED

**Comment by hrngok** [comment]
------> RESOLVED (certain buildings had the same intervenant twice and this was not accounted for)

For some intervenants the auto calculation of the buildings does not match with the building numbers on the page. Here an example:
![resim](https://user-images.githubusercontent.com/38464805/88781743-0c966c00-d18d-11ea-9b2a-692d3e19c149.png) 

When we click on 'Willy VAN DER MEEREN' tag or seach for him we see that he has 117 buildings instead of 118. In the last page of the buildings he has only 2 buildings. 
![resim](https://user-images.githubusercontent.com/38464805/88782283-b118ae00-d18d-11ea-8d34-3d797ecff784.png)

In my opinion, it might happen due to duplications in "INTERVENANTS" column or it is a parsing issue. Probably some intervenants' names include extra white space at the beginning of the names. When I check results with Python Pandas it shows the number of intervenants as 117 
![resim](https://user-images.githubusercontent.com/38464805/88782725-369c5e00-d18e-11ea-974f-013e1a3b249a.png)

------> RESOLVED (certain buildings had the same intervenant twice and this was not accounted for)

**Comment by Speedbuilder** [comment]
Closed issue
